- name: Adicionando PPA do php 7.1
  become: yes
  apt_repository:
    validate_certs: no
    repo: 'ppa:ondrej/php'
    state: present
    update_cache: yes

- name: Instalando php e dependências
  become: yes
  apt:
    pkg:
    - php7.3-fpm
    - php7.3
    - php7.3-mysql
    - php7.3-soap
    - php7.3-bcmath
    - php7.3-xml
    - php7.3-mbstring
    - php7.3-gd
    - php7.3-common
    - php7.3-cli
    - php7.3-curl
    - php7.3-intl
    - php7.3-zip
    - zip
    - unzip

- name: Iniciando serviço PHP FPM
  service:
    name: php7.3-fpm
    state: started
    enabled: yes

