- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_rsa

- name: Atualizando as chaves ssh publica no arquivo autorized_keys e travando um backup
  become: yes
  ignore_errors: yes
  ansible.builtin.shell: mv /home/vagrant/.ssh/authorized_keys /home/vagrant/.ssh/authorized_keys.bak && chattr +i /home/vagrant/.ssh/authorized_keys.bak && cat /home/vagrant/.ssh/authorized_keys.bak > /home/vagrant/.ssh/authorized_keys && cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
