---
- name: Playbook de instalação do Magento 2.3.4 e seus requisitos
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - configs
    - mysql
    - php
    - nginx
    - composer
    - magento2
